### ISSUE TITLE
depend on stow

### ISSUE THREAD

**Issue by ghost** [lihop/nixos#1]
since your dotfiles script depends on stow, shouldn't this package declare a stow dep?

**Comment by lihop** [comment]
I just checked and there is a stow package declared in the workstation role:
https://github.com/lihop/nixos/blob/master/roles/workstation.nix#L20

I guess I only ever installed the dotfiles on my chromebook and desktop (not on the VPS) and both of these devices had the workstation role so the dotfiles script worked.
